### Variables
@baseUrl = http://localhost:8084/api/v1
@contentType = application/json
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMTYxYTNiMTMtMzRmMy00MjJkLWI5YWEtYzIxNmQ4MTNkMTBmIiwiZW1haWwiOiJ1c2VyQGV4YW1wbGUuY29tIiwicm9sZXMiOlsidXNlciJdLCJleHAiOjE3NjQwNjg1NjksImlhdCI6MTc2Mzk4MjE2OX0.InAj2RzTxP2ORBcaJhxTniyISys8_QHmLxIlbTW1abs

### Purchase Ticket
POST {{baseUrl}}/tickets/purchase
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "event_id": "161a3b13-34f3-422d-b9aa-c216d813d10f",
  "quantity": 2,
  "payment_method": "credit_card"
}

### Get My Orders
GET {{baseUrl}}/tickets/my-orders
Authorization: Bearer {{token}}

### Get My Orders with Pagination
GET {{baseUrl}}/tickets/my-orders?page=1&limit=10
Authorization: Bearer {{token}}

###