// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/baramulti/ticketing-system/backend/internal/models"
	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// TicketRepository is an autogenerated mock type for the TicketRepository type
type TicketRepository struct {
	mock.Mock
}

// CreateOrder provides a mock function with given fields: ctx, order
func (_m *TicketRepository) CreateOrder(ctx context.Context, order *models.TicketOrder) error {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.TicketOrder) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateTickets provides a mock function with given fields: ctx, tickets
func (_m *TicketRepository) CreateTickets(ctx context.Context, tickets []*models.Ticket) error {
	ret := _m.Called(ctx, tickets)

	if len(ret) == 0 {
		panic("no return value specified for CreateTickets")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*models.Ticket) error); ok {
		r0 = rf(ctx, tickets)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindOrderByID provides a mock function with given fields: ctx, id
func (_m *TicketRepository) FindOrderByID(ctx context.Context, id string) (*models.TicketOrder, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindOrderByID")
	}

	var r0 *models.TicketOrder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.TicketOrder, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.TicketOrder); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TicketOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindTicketsByOrderID provides a mock function with given fields: ctx, orderID
func (_m *TicketRepository) FindTicketsByOrderID(ctx context.Context, orderID string) ([]*models.Ticket, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for FindTicketsByOrderID")
	}

	var r0 []*models.Ticket
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*models.Ticket, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.Ticket); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Ticket)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListOrdersByUserID provides a mock function with given fields: ctx, userID
func (_m *TicketRepository) ListOrdersByUserID(ctx context.Context, userID string) ([]*models.TicketOrder, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListOrdersByUserID")
	}

	var r0 []*models.TicketOrder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*models.TicketOrder, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.TicketOrder); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.TicketOrder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateOrderStatus provides a mock function with given fields: ctx, orderID, status
func (_m *TicketRepository) UpdateOrderStatus(ctx context.Context, orderID string, status models.TicketOrderStatus) error {
	ret := _m.Called(ctx, orderID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, models.TicketOrderStatus) error); ok {
		r0 = rf(ctx, orderID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithTransaction provides a mock function with given fields: ctx, fn
func (_m *TicketRepository) WithTransaction(ctx context.Context, fn func(*sql.Tx) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(*sql.Tx) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTicketRepository creates a new instance of TicketRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTicketRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TicketRepository {
	mock := &TicketRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
